language: swift
xcode_project: Kryptonite.xcodeproj
xcode_scheme: Debug
osx_image: xcode8.3
git:
    submodules: false
before_install:
  # pin github.com public key for travis
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
  - git submodule update --init --recursive
before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:$HOME/.cargo/bin/
  - rustup target add aarch64-apple-ios
  - rustup target add armv7-apple-ios
  - rustup target add armv7s-apple-ios
  - rustup target add x86_64-apple-ios
  - rustup target add i386-apple-ios
  - rustup update
  - cargo install cargo-lipo
  - sudo gem install xcpretty
script:
  - make check
